### PR TITLE
Sim sss detection publisher

### PR DESCRIPTION
**Pull request by luxiya01**
Mock buoy detection based on distance and angle from the robot.

### CODE REVIEW

**Comment by nilsbore** [comment]
This is the wrong repo for this kind of thing IMHO. Sim packages simulate the basic robots, not advanced capabilities such as this. I think a good place for it would be in smarc_perception. I could probably be convinced otherwise, but then I need some good arguments :).

**Comment by luxiya01** [comment]
Yeah, I see where you are coming from. I put the sim object detection here since it is part of the simulation and doesn't really involve "real" perception, which I was planning to use `smarc_perception` package for. But indeed, I have no objections of splitting the smarc_perception repo into `simulation` and `real` packages, and moving the mock object detection there :)

**Comment by nilsbore** [comment]
That sounds like a good plan! I think you could even have sim and real scripts within the same rope detection package in smarc_perception.

**Comment by luxiya01** [comment]
Sounds like a good idea!

**Pull request closed without merging**
